---
title: Analysis
author: "Jingyi Yao"
date: "`r Sys.Date()`"
output: github_document
---

```{r,message=FALSE,warning=FALSE}
library(tidyverse)
```


```{r}
data = read_csv("./data/Merged_expectation.csv")

```


## 1. Average Life Expectancy by Year (2000 - 2016)
```{r}
data %>% 
  janitor::clean_names() %>% 
  group_by(year) %>% 
  summarise(avg_by_year = mean(life_expect,na.rm = T)) %>% 
  ggplot(aes(x = year,y = avg_by_year)) +
  geom_point() +
  geom_line()

```

## 2. Average Life Expectation by Regions
```{r}
data %>% 
  janitor::clean_names() %>% 
  group_by(region) %>% 
  summarise(avg_by_region = mean(life_expect,na.rm = T)) %>% 
  arrange(avg_by_region) %>% 
  knitr::kable(digits = 3)
```


## 3. Average Life Expectancy by (region, year) Combination
```{r}
data %>% 
  janitor::clean_names() %>% 
  group_by(region,year) %>% 
  summarise(avg_by_year_region = mean(life_expect,na.rm = T)) %>% 
  knitr::kable(digits = 3)

```

```{r}
# tidy data in another form that might be useful

data %>% 
  janitor::clean_names() %>% 
  group_by(region,year) %>% 
  summarise(avg_by_year_region = mean(life_expect,na.rm = T)) %>% 
  pivot_wider(
    names_from = region,
    values_from = avg_by_year_region
  ) %>% 
  knitr::kable(digits = 3)

```

## 4. ANOVA to Test the Difference in Mean Life Expectancy among Regions
```{r}
exp_year_region <- data %>% 
  janitor::clean_names() %>% 
  group_by(region,year) %>% 
  summarise(avg_by_year_region = mean(life_expect,na.rm = T)) 

anova_result = aov(avg_by_year_region ~ factor(region),data = exp_year_region)
broom::tidy(anova_result) %>% 
    knitr::kable()


```

## 5. Multiple Comparison Methods to Find the Difference in Regions

### Bonferroni's Method
```{r}
bonferroni_result <- pairwise.t.test(exp_year_region$avg_by_year_region, exp_year_region$region, p.adj = 'bonferroni')

broom::tidy(bonferroni_result) %>% 
    knitr::kable()

```

### Tukey's Method
```{r}
tukey_result <- TukeyHSD(anova_result)

plot(tukey_result)

```


```{r}



```




