---
title: "EDA-correlation"
author: "Yuchen Zhang"
date: "2022-11-27"
output: html_document
---

```{r}
library(tidyverse)
library(corrplot)
```



```{r}
merged_data = 
  read_csv("data/Merged_expectation.csv", show_col_types = FALSE) %>% 
  filter(year == 2015) %>% 
  select(-...1,-country_code,-country,-region,-year,-life_exp60,-income_group,-`Developed / Developing Countries`)


merged_data
```


```{r}
mortality_correlation = merged_data %>% 
  select(adult_mortality, infant_mort, age1_4mort, une_life)
res = cor(mortality_correlation)
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}
disease_correlation = merged_data %>% 
  select(hepatitis, measles, polio, diphtheria)
res = cor(disease_correlation)
res
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}
obe_thin_correlation = merged_data %>% 
  select(age5_19thinness, age5_19obesity)
res = cor(obe_thin_correlation)
res
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}
gdp_gni_correlation = merged_data %>% 
  select(che_gdp, une_gni)
res = cor(gdp_gni_correlation)
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

