---
title: "Imputation"

output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(dbplyr))
options(tibble.print_min = 5)

```

# Background Information of the data

First, we load and merge the data:
```{r,message=FALSE, warning=FALSE}
country_code = 
  read_csv("data/country-codes.csv", show_col_types = FALSE) %>% 
  select(`ISO3166-1-Alpha-3`, `Developed / Developing Countries`)



#Guess the column type of life expectancy data
LifeExpectancy = read_csv("data/who_life_exp.csv",col_types = cols(.default = col_guess())) %>% 
  janitor::clean_names()

merged_data_PM = merge(LifeExpectancy, country_code, by.x = "country_code", by.y = "ISO3166-1-Alpha-3" )
```

pm 2.5
```{r,message=FALSE, warning=FALSE}

#read pm2.5 data
PM_dataset = 
  read_csv("data/pm2.5.csv", show_col_types = FALSE, skip = 4) 

PM_dataset_clean = 
  PM_dataset %>% 
  janitor::clean_names() %>% 
  select(-(x1960:x1999),-(x2017:x2021)) %>% 
  pivot_longer(
    x2000:x2016,
    names_to = "year",
    names_prefix = "x",
    values_to = "PM_value"
  ) %>% 
  select(country_code, year, PM_value) %>% 
  mutate(year = as.numeric(year))
```

Developed / Developing Countries
```{r,message=FALSE, warning=FALSE}
#merged data with developed/ developing countries
merged_data_d = 
  merged_data_PM %>% 
  left_join(PM_dataset_clean, by = c("country_code","year"))
```

income level
```{r,message=FALSE, warning=FALSE}
#read income level data
Income_dataset = read_csv("data/income_level.csv", show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  select(country_code,income_group)

#merged data with income level
merged_data_i = merged_data_d %>% 
  left_join( Income_dataset, by = c("country_code")) %>% 
  select(country_code:une_school,PM_value,income_group,`Developed / Developing Countries`)
```

Health expenditure
```{r,message=FALSE, warning=FALSE}
health_exp = read_csv("data/government_compulsory_health expenditure_from_1970_2020.csv") %>% 
  janitor::clean_names() %>% 
  filter(measure=="PC_GDP") %>% 
  mutate("country_code"=location,
         "year" = time) %>% 
  select(country_code,year, value)

merged_data = 
  merged_data_i %>% 
  left_join(health_exp, by = c("country_code","year")) %>% 
  mutate("health_exp" = value) %>% 
  select(country_code:une_school,PM_value,income_group,health_exp,`Developed / Developing Countries`)
```


# Impute

```{r,message=FALSE, warning=FALSE}
raw_mat = 
  merged_data %>% 
  select(-country, -country_code, -region,-income_group, -`Developed / Developing Countries`) %>% 
  as.matrix()

imputed_mat = filling::fill.KNNimpute(raw_mat, k = 2)

```

```{r}
#colnames_exp = colnames(LifeExpectancy)
Imputed_expectancy = merged_data
for (i in 1:(length(merged_data)-5)) {
  Imputed_expectancy[i+3][[1]] = imputed_mat[[1]][,i]
}
head(Imputed_expectancy)

```

```{r}
write.csv(merged_data , file = "data/Merged_expectation.csv")
write.csv(Imputed_expectancy , file = "data/Imputed_expectation.csv")

```





