<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Linear Regression and Clustering</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Introduction.html">Introduction</a>
</li>
<li>
  <a href="Imputation.html">Data</a>
</li>
<li>
  <a href="EDA.html">EDA</a>
</li>
<li>
  <a href="analysis.html">Prelimary Analysis</a>
</li>
<li>
  <a href="Linear_Regression_Model.html">Regression</a>
</li>
<li>
  <a href="Conclusion.html">Conclusion</a>
</li>
<li>
  <a href="https://7lx8uo-txbrook.shinyapps.io/map_dashboard/#section-life-expectancy">Shiny App</a>
</li>
<li>
  <a href="Project-report.html">Report</a>
</li>
<li>
  <a href="mailto:sx2337@cumc.columbia.edu?subject=About%20your%20website">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/ShunXie/SX.github.io/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Linear Regression and Clustering</h1>

</div>


<pre class="r"><code>library(tidyverse)
library(dplyr)
library(car)
library(modelr)
library(mgcv)
library(patchwork)
library(factoextra)</code></pre>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>After our EDA and statistical analysis, we consider to generate a
linear regression to better express the relationship between Life
Expectancy and other variables. In particular, we set une_life as our
response variable and we only look at the year of 2015.</p>
<p><br></p>
</div>
<div id="dataset-preparation" class="section level1">
<h1>Dataset Preparation</h1>
<p>In the beginnig, to prepare our dataset for multiple linear
regression, we delete mortality related variables, delete une_pop, which
is not a good predictor of life expenctancy, and also delete variables
that have high correlation values presented in EDA section.
Specifically, we use “measles” to be the representative of vaccination
variables–hepatitis, measles, polio, and diphtheria. Moreover, we use
“bmi” to be another representative of age5_19thinness, age5_19obesity,
and bmi.</p>
<p>In the end, we limit the data to year 2015, and set the Income
Reference Group to Low Income.</p>
<pre class="r"><code>data &lt;-
  read_csv(&quot;data/Merged_expectation.csv&quot;) %&gt;%
  filter(year == 2015) %&gt;% 
  select(alcohol:percent_w_in_lower_house) %&gt;% 
  select(-hepatitis, -polio, -diphtheria, -age5_19thinness, -age5_19obesity, -une_infant, -une_pop) %&gt;% 
  mutate(income_group = as.factor(income_group),
         income_group = relevel(income_group, ref = &quot;Low income&quot;))</code></pre>
<p><br></p>
</div>
<div id="model-1" class="section level1">
<h1>Model 1</h1>
<p>First, we look at the number of missing data we have on each column,
at year 2015. The table below shows variables that have less than 5%
NA’s.</p>
<pre class="r"><code>NA_table_1 &lt;- data %&gt;% 
  is.na() %&gt;% 
  colSums()
NA_table_1[NA_table_1 &lt;= 10] %&gt;% 
    knitr::kable(col.names = c(&quot;Counts of NA&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Counts of NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">alcohol</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">bmi</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">measles</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">basic_water</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">gghe_d</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left">che_gdp</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="left">une_life</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">une_gni</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="left">PM_value</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">income_group</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Developed / Developing Countries</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">percent_w_in_lower_house</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
<p>Limited to the variables that we have less than 5% NA’s (which is
less than 10 NAs), also exclude variables that have high correlation
value, we could generate our first basic linear model, with selected
variables of alcohol, bmi, measles, basic_water, che_gdp (health
expenditure per gdp, gghe_d is deleted since it represents similar
aspects), une_gni, PM_value, income_group (Developed/Developing
Countries is deleted since it is similar to income_group),
percent_w_in_lower_house, and our response variable of une_life.</p>
<ul>
<li>Model 1: une_life ~ alcohol + bmi + measles + basic_water + che_gdp
+ une_gni + PM_value + income_group * percent_w_in_lower_house</li>
</ul>
<p>The following table shows the distribution of all numerical variables
here.</p>
<pre class="r"><code>colname &lt;- c(&quot;alcohol&quot;, &quot;bmi&quot;, &quot;measles&quot;, &quot;basic_water&quot;, &quot;che_gdp&quot;, &quot;une_gni&quot;, &quot;PM_value&quot;, &quot;percent_w_in_lower_house&quot;)
par(mfrow=c(2, 4))
data_1_a &lt;- data.frame(data)
for (i in 1:8) {
  variable &lt;- data_1_a[colname[i]][ ,1]
  hist(variable, main = paste(&quot;Histogram of&quot;, colname[i], sep = &quot; &quot;), xlab = colname[i])
}</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Delete all the NA rows in the data, consider intersection between
income_group and percent_w_in_lower_house, using step function with
backwards direction. Then we generate our first model.</p>
<pre class="r"><code># delete all the Na columns
data_1 &lt;- data %&gt;% 
  select(une_life, alcohol, bmi, measles, basic_water, che_gdp, une_gni, PM_value, income_group, percent_w_in_lower_house) %&gt;% 
  drop_na()</code></pre>
<pre class="r"><code># fit the model one
m &lt;- lm(une_life ~ alcohol + bmi + measles + basic_water + che_gdp + une_gni + PM_value + income_group * percent_w_in_lower_house, data = data_1)
# use stepwise function
m1 &lt;- step(m, direction = &quot;backward&quot;, trace = FALSE)</code></pre>
<pre class="r"><code># create table for regression output
m1 %&gt;%
  summary() %&gt;%
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(
      caption = &quot;Estimate and P-value of Model 1 for Year 2015 Life Expectancy (Income Reference Group is Low Income)&quot;, 
      col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;P-value&quot;),
      digits = 3
  )</code></pre>
<table>
<caption>Estimate and P-value of Model 1 for Year 2015 Life Expectancy
(Income Reference Group is Low Income)</caption>
<colgroup>
<col width="77%" />
<col width="12%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">Estimate</th>
<th align="right">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">37.297</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">alcohol</td>
<td align="right">-0.164</td>
<td align="right">0.102</td>
</tr>
<tr class="odd">
<td align="left">measles</td>
<td align="right">0.066</td>
<td align="right">0.035</td>
</tr>
<tr class="even">
<td align="left">basic_water</td>
<td align="right">0.271</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">income_groupHigh income</td>
<td align="right">6.368</td>
<td align="right">0.009</td>
</tr>
<tr class="even">
<td align="left">income_groupLower middle income</td>
<td align="right">3.437</td>
<td align="right">0.068</td>
</tr>
<tr class="odd">
<td align="left">income_groupUpper middle income</td>
<td align="right">4.358</td>
<td align="right">0.065</td>
</tr>
<tr class="even">
<td align="left">percent_w_in_lower_house</td>
<td align="right">0.156</td>
<td align="right">0.012</td>
</tr>
<tr class="odd">
<td align="left">income_groupHigh income:percent_w_in_lower_house</td>
<td align="right">-0.003</td>
<td align="right">0.973</td>
</tr>
<tr class="even">
<td align="left">income_groupLower middle
income:percent_w_in_lower_house</td>
<td align="right">-0.151</td>
<td align="right">0.041</td>
</tr>
<tr class="odd">
<td align="left">income_groupUpper middle
income:percent_w_in_lower_house</td>
<td align="right">-0.152</td>
<td align="right">0.054</td>
</tr>
</tbody>
</table>
<p>From the above, variables like bmi, che_gdp, une_gni, PM_value are
deleted according to backwards step function. One way to explain this is
that these variables have high correlation with income_group–in higher
income countries(une_gni), people have more access to healthy foods and
healthy life styles (bmi), governments also spend more money on public
health(che_gdp), as well as on building a clean
environment(PM_value).</p>
<p>From the estimates, we can conclude that, increase of alcohol
consumption has negative effects on life expectancy. Increasing access
to vaccines and clean water, the empowerment of women, and higher income
will lead to a longer life.</p>
<p>Another thing that needs to be aware of is that the intersection of
income group and women in parliament(percent_w_in_lower_house). The
variable percent_w_in_lower_house is significant itself, but it is more
significant in middle income and upper income groups. In other words,
after a country reaches a certain level of income, increasing women’s
voice in the country actually helps people live longer, which follows
the intention that we chose to include this variable in the first place.
(Since 0.156 - 0.152 &gt; 0, keeping other variables constant,
percent_w_in_lower_house increases, the predicted life expectancy will
increase.)</p>
<p>The model 1’s R-adjusted score reaches 0.7808107.</p>
<p>Below are the analysis plots of the model. These plot shows that the
residuals are normally distributed, independent, but may not have a
constant variance–it has a linear trend in the end according to the
third plot. In second plot, the points follows the line, so the
regression function is linear. Therefore, maybe we don’t need to add
transformation to our response variable.</p>
<pre class="r"><code>par(mfrow=c(2,2))
plot(m1)</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<ul>
<li>The final Model 1 is une_life ~ alcohol + measles + basic_water +
income_group * percent_w_in_lower_house</li>
</ul>
<p><br> <br></p>
</div>
<div id="model-2" class="section level1">
<h1>Model 2</h1>
<p>Second, we only look at the countries with existing une_literacy data
and found out the number of NA in other variables of these countries, at
year 2015. The table below shows variables that have less than 5%
NA’s.</p>
<pre class="r"><code>NA_table_2 &lt;- data %&gt;% 
  filter(is.na(une_literacy) == FALSE) %&gt;% 
  is.na() %&gt;% 
  colSums()
NA_table_2[NA_table_2 &lt;= 3] %&gt;% 
    knitr::kable(col.names = c(&quot;Counts of NA&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Counts of NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">alcohol</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">bmi</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">measles</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">basic_water</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">gghe_d</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">che_gdp</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">une_life</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">une_gni</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">une_literacy</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">PM_value</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">income_group</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Developed / Developing Countries</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">percent_w_in_lower_house</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
<p>Here, limited to the variable that we have less than 5% NA’s (which
is less than 3 NAs), also exclude variables that have high correlation
value, we could generate our second basic linear model, with selected
variables of alcohol, bmi, measles, basic_water, che_gdp, une_gni,
une_literacy, PM_value, income_group, percent_w_in_lower_house, and our
response variable of une_life.</p>
<ul>
<li>Model 2: une_life ~ alcohol + bmi + measles + basic_water + che_gdp
+ une_gni + une_literacy + PM_value + income_group +
percent_w_in_lower_house + income_group * percent_w_in_lower_house</li>
</ul>
<p>(Also consider intersection here)</p>
<p>The following table shows the distribution of all numerical variables
here.</p>
<pre class="r"><code># delete all the Na columns, and limit to countries with existing une_literacy data
data_2 &lt;- data %&gt;% 
  filter(is.na(une_literacy) == FALSE) %&gt;% 
  select(une_life, alcohol, bmi, measles, basic_water, che_gdp, une_gni, une_literacy, PM_value, income_group, percent_w_in_lower_house) %&gt;% 
  drop_na()</code></pre>
<pre class="r"><code>colname &lt;- c(&quot;alcohol&quot;, &quot;bmi&quot;, &quot;measles&quot;, &quot;basic_water&quot;, &quot;che_gdp&quot;, &quot;une_gni&quot;, &quot;une_literacy&quot;, &quot;PM_value&quot;, &quot;percent_w_in_lower_house&quot;)
par(mfrow=c(3, 3))
data_2_a &lt;- data.frame(data_2)
for (i in 1:9) {
  variable &lt;- data_2_a[colname[i]][ ,1]
  hist(variable, main = paste(&quot;Histogram of&quot;, colname[i], sep = &quot; &quot;), xlab = colname[i])
}</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Delete all the NA rows in the data, consider intersection between
income_group and percent_w_in_lower_house, using step function with
backwards direction. Then we generate our second model.</p>
<pre class="r"><code># fit the model two
m &lt;- lm(une_life ~ alcohol + bmi + measles + basic_water + che_gdp + une_gni + une_literacy + PM_value + income_group * percent_w_in_lower_house, data = data_2)
# use stepwise function
m2 &lt;- step(m, direction = &quot;backward&quot;, trace = FALSE)</code></pre>
<pre class="r"><code># create table for regression output
m2 %&gt;%
  summary() %&gt;%
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(
      caption = &quot;Estimate and P-value of Model 2 for Year 2015 Life Expectancy Only in Countries With Existing Literacy Data&quot;, 
      col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;P-value&quot;),
      digits = 3
  )</code></pre>
<table>
<caption>Estimate and P-value of Model 2 for Year 2015 Life Expectancy
Only in Countries With Existing Literacy Data</caption>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">Estimate</th>
<th align="right">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">48.798</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">bmi</td>
<td align="right">-0.521</td>
<td align="right">0.126</td>
</tr>
<tr class="odd">
<td align="left">measles</td>
<td align="right">0.102</td>
<td align="right">0.100</td>
</tr>
<tr class="even">
<td align="left">basic_water</td>
<td align="right">0.185</td>
<td align="right">0.002</td>
</tr>
<tr class="odd">
<td align="left">che_gdp</td>
<td align="right">0.464</td>
<td align="right">0.088</td>
</tr>
<tr class="even">
<td align="left">income_groupHigh income</td>
<td align="right">13.186</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">income_groupLower middle income</td>
<td align="right">6.742</td>
<td align="right">0.005</td>
</tr>
<tr class="even">
<td align="left">income_groupUpper middle income</td>
<td align="right">8.695</td>
<td align="right">0.002</td>
</tr>
</tbody>
</table>
<p>From the above, variables like alcohol, une_gni, une_literacy,
PM_value, income_group:percent_w_in_lower_houseare,
percent_w_in_lower_houseare are deleted according to backwards step
function. It is very different from the model 1 when we limit to 37
countries. Moreover, even though we specifically make sure every country
has literacy data, literacy is not significant enough to be included in
the linear regression model.</p>
<p>The intersection of income group and women in
parliament(percent_w_in_lower_house) is also been deleted. Therefore, we
can conclude that the model we generate in a small range of countries
with complete literacy data entries is very different from the model
generated from a larger dataset, while literacy data is not significant
in the small range of countries. To conclude, we should discard literacy
variable, and also discard model 2.</p>
<p>The model 2’s R-adjusted score reaches 0.857607. This is reasonable,
since we generate model 2 in a small range of countries.</p>
<ul>
<li>Therefore, we should discard literacy variable, and also discard
model 2. We should consider Model 1 as a great subset of the full
model.</li>
</ul>
<p><br> <br></p>
</div>
<div id="compare-model-1-with-full-model" class="section level1">
<h1>Compare Model 1 with Full Model</h1>
<p>Full Model is the Year 2015 full dataset except mortality rate and
except variables with more than 5% NAs.</p>
<ul>
<li>Full Model: uni_life ~ hepatitis + polio + diphtheria +
age5_19thinness + age5_19obesity + une_pop + alcohol + bmi + measles +
basic_water + gghe_d + che_gdp + une_pop + une_gni + PM_value +
income_group + percent_w_in_lower_house + Developed/Developing
Countries</li>
</ul>
<pre class="r"><code># generate the Year 2015 full dataset except mortality rate
data_full &lt;-
  read_csv(&quot;data/Merged_expectation.csv&quot;) %&gt;% 
  filter(year == 2015) %&gt;% 
  select(une_life, hepatitis, polio, diphtheria, age5_19thinness, age5_19obesity, une_pop , alcohol, bmi, measles, basic_water, gghe_d, che_gdp, une_pop, une_gni, PM_value, income_group, percent_w_in_lower_house, `Developed / Developing Countries`) %&gt;%
  drop_na()
m_full &lt;- lm(une_life ~ ., data = data_full)</code></pre>
<pre class="r"><code>m1 %&gt;%
  summary() %&gt;% 
  broom::glance() %&gt;%
  bind_rows(summary(m_full) %&gt;% broom::glance()) %&gt;%
  mutate(model = c(&quot;Model 1&quot;, &quot;Full Model&quot;)) %&gt;%
  select(model, everything()) %&gt;% 
  knitr::kable(
      caption = &quot;Comparision of Model 1 and Full Model&quot;, 
      digits = 3
  )</code></pre>
<table>
<caption>Comparision of Model 1 and Full Model</caption>
<colgroup>
<col width="13%" />
<col width="12%" />
<col width="17%" />
<col width="7%" />
<col width="12%" />
<col width="10%" />
<col width="3%" />
<col width="15%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Model 1</td>
<td align="right">0.794</td>
<td align="right">0.781</td>
<td align="right">3.693</td>
<td align="right">59.777</td>
<td align="right">0</td>
<td align="right">10</td>
<td align="right">155</td>
<td align="right">166</td>
</tr>
<tr class="even">
<td align="left">Full Model</td>
<td align="right">0.817</td>
<td align="right">0.791</td>
<td align="right">3.541</td>
<td align="right">31.710</td>
<td align="right">0</td>
<td align="right">19</td>
<td align="right">135</td>
<td align="right">155</td>
</tr>
</tbody>
</table>
<p>From the above table, Model 1 and Full Model do not have big
difference on adjusted R^2, but Model 1 has less predictors, which is
much better.</p>
<p><br> <br></p>
</div>
<div id="transformation-on-response-variable-of-model-1"
class="section level1">
<h1>Transformation on Response Variable of Model 1</h1>
<p>First, we want to find whether response variable une_life needs
transformation.</p>
<pre class="r"><code>inverseResponsePlot(m1, key = TRUE)</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre><code>##     lambda      RSS
## 1  2.17794 1637.306
## 2 -1.00000 1953.745
## 3  0.00000 1782.892
## 4  1.00000 1678.616</code></pre>
<p>From the above plot, the best <span
class="math inline">\(\lambda\)</span> for model 1 is 2.17794, which is
different from 1. Therefore, we will apply <span
class="math inline">\(\lambda\)</span> equal to 2.17794 to une_life.</p>
<pre class="r"><code># Fit model 1 with une_life^2.17794
m1_tr &lt;- lm((une_life)^2.17794 ~ alcohol + measles + basic_water + income_group * percent_w_in_lower_house, data = data_1)
# create table for regression output
m1_tr %&gt;%
  summary() %&gt;%
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(
      caption = &quot;Estimate and P-value of Transformed Model 1 for Year 2015 Life Expectancy&quot;, 
      col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;P-value&quot;),
      digits = 3
  )</code></pre>
<table>
<caption>Estimate and P-value of Transformed Model 1 for Year 2015 Life
Expectancy</caption>
<colgroup>
<col width="77%" />
<col width="12%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">Estimate</th>
<th align="right">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">695.168</td>
<td align="right">0.403</td>
</tr>
<tr class="even">
<td align="left">alcohol</td>
<td align="right">-52.404</td>
<td align="right">0.099</td>
</tr>
<tr class="odd">
<td align="left">measles</td>
<td align="right">19.506</td>
<td align="right">0.047</td>
</tr>
<tr class="even">
<td align="left">basic_water</td>
<td align="right">82.789</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">income_groupHigh income</td>
<td align="right">1960.037</td>
<td align="right">0.011</td>
</tr>
<tr class="even">
<td align="left">income_groupLower middle income</td>
<td align="right">942.528</td>
<td align="right">0.112</td>
</tr>
<tr class="odd">
<td align="left">income_groupUpper middle income</td>
<td align="right">1248.515</td>
<td align="right">0.093</td>
</tr>
<tr class="even">
<td align="left">percent_w_in_lower_house</td>
<td align="right">43.753</td>
<td align="right">0.025</td>
</tr>
<tr class="odd">
<td align="left">income_groupHigh income:percent_w_in_lower_house</td>
<td align="right">12.999</td>
<td align="right">0.603</td>
</tr>
<tr class="even">
<td align="left">income_groupLower middle
income:percent_w_in_lower_house</td>
<td align="right">-42.804</td>
<td align="right">0.065</td>
</tr>
<tr class="odd">
<td align="left">income_groupUpper middle
income:percent_w_in_lower_house</td>
<td align="right">-41.973</td>
<td align="right">0.091</td>
</tr>
</tbody>
</table>
<p>The transformed model 1’s R-adjusted score reaches 0.7886281. The
adjusted R square increases ~0.01 after transformation, which is close
to the adjusted R square of the full model. However, while the
difference of adjusted R square is small, for better interpretation, we
decide to choose the original Model 1.</p>
<p>Finally, our linear regression model on life expectancy is une_life ~
alcohol + measles + basic_water + income_group *
percent_w_in_lower_house.</p>
<p><br> <br></p>
</div>
<div id="cross-validation" class="section level1">
<h1>Cross Validation</h1>
<ul>
<li>Model: une_life ~ alcohol + measles + basic_water + income_group *
percent_w_in_lower_house.</li>
</ul>
<p>We divides the Year 2015 dataset to train ans test two datasets 100
times. The graph below shows RMSE distribution in test datasets.</p>
<pre class="r"><code># generate a cv dataframe 
cv_df &lt;-
  crossv_mc(data_1, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
# fit the model to the generated CV dataframe
cv_df &lt;-
  cv_df %&gt;% 
  mutate(
    model  = map(train, ~lm(une_life ~ alcohol + measles + basic_water + income_group * percent_w_in_lower_house, data = .x)),
    rmse = map2_dbl(model, test, ~rmse(model = .x, data = .y)))
# plot the prediction error
cv_df %&gt;% 
  select(rmse) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;) %&gt;% 
  ggplot(aes(x= model, y = rmse)) + 
  geom_violin() +
  labs(
    title = &quot;Prediction Errors For Our Model Under CV&quot;,
    x = &quot;Model 1&quot;,
    y = &quot;Prediction Errors&quot;
  ) </code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>From the plot, RMSE is around 4.0, and spreads from 3.0 to 5.0, which
is relatively a small and concentrated RMSE.</p>
<p><br> <br></p>
</div>
<div id="prediction" class="section level1">
<h1>Prediction</h1>
<p>The below graphs will show our prediction on Year 2016 data. Since we
only have percent_w_in_lower_house data in year 2015, we will still use
the same value for year 2016.</p>
<pre class="r"><code># predict on merged_data year 2016
data_2016 &lt;-
  read_csv(&quot;data/Merged_expectation.csv&quot;) %&gt;%
  filter(year == 2016) %&gt;% 
  select(une_life, alcohol, measles, basic_water, income_group) %&gt;% 
  bind_cols(data[&quot;percent_w_in_lower_house&quot;]) %&gt;% 
  drop_na() %&gt;% 
  mutate(income_group = as.factor(income_group),
         income_group = relevel(income_group, ref = &quot;Low income&quot;))
prediction_2016 &lt;- predict(m1, newdata = data_2016)
# draw ggplot1
ggp1 &lt;- prediction_2016 %&gt;% 
  bind_cols(data_2016[&quot;une_life&quot;])  %&gt;% 
  ggplot(aes(x = une_life, y = prediction_2016)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1, color = &quot;red&quot;) +
  labs(
    title = &quot;Prediction V.S. Actual Life Expectancy On Year 2016 In Original Dataset&quot;,
    x = &quot;Actual Life Expectancy&quot;,
    y = &quot;Prediction&quot;
  )

# predict on imputed_data year 2016
data_2016_im &lt;-
  read_csv(&quot;data/Imputed_expectation.csv&quot;) %&gt;%
  filter(year == 2016) %&gt;% 
  select(une_life, alcohol, measles, basic_water, income_group) %&gt;% 
  bind_cols(data[&quot;percent_w_in_lower_house&quot;]) %&gt;% 
  drop_na() %&gt;% 
  mutate(income_group = as.factor(income_group),
         income_group = relevel(income_group, ref = &quot;Low income&quot;))
prediction_2016_im &lt;- predict(m1, newdata = data_2016_im)
# draw ggplot2
ggp2 &lt;- prediction_2016_im %&gt;% 
  bind_cols(data_2016_im[&quot;une_life&quot;])  %&gt;% 
  ggplot(aes(x = une_life, y = prediction_2016_im)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1, color = &quot;red&quot;) +
  labs(
    title = &quot;Prediction V.S. Actual Life Expectancy On Year 2016 In Imputed Dataset&quot;,
    x = &quot;Actual Life Expectancy&quot;,
    y = &quot;Prediction&quot;
  )
ggp1 / ggp2</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The graph above is shown that almost every prediction is in a + or -
5 years range, and there is no difference in imputed dataset and
original dataset–possibly there is no data imputed on these variables of
Year 2016.</p>
<p>If we consider a range in 3 years (+ or - 1.5 years) is a good
prediction, lets see the percentage of predicted life expectancy in this
range on Year 2016.</p>
<pre class="r"><code>actual &lt;- data_2016[&quot;une_life&quot;]
percent &lt;- sum(prediction_2016 &gt;= actual - 1.5 &amp; prediction_2016 &lt;= actual + 1.5) / length(prediction_2016)
paste(&quot;The calculated result is &quot;, round(percent, 3), &quot;.&quot;)</code></pre>
<pre><code>## [1] &quot;The calculated result is  0.369 .&quot;</code></pre>
<p>Therefore, if we consider a range in 3 years (+ or - 1.5 years) is a
good prediction, 0.369 of predicted life expectancy will be in this
range on Year 2016.</p>
<p><br> <br></p>
</div>
<div id="clustering" class="section level1">
<h1>Clustering</h1>
<p>Clustering Analysis is an unsupervised method that cluster the
countries of interest into groups in a high dimensional vector space,
based on the information of predictors values, i.e. alcohol consumption,
bmi value, measle vaccinations and etc in our analysis. Different from
prediction, we focus on how countries are correlated with each other
based on their predictors and more importantly, the optimal number of
groups we can partition into based on all predictors. Based on the
optimal number of groups, we can essentially impute our model using k
mean clustering method. In our data cleaning, we impute our data using
k=4. Here, we check whether k=4 is a good choice based on k mean
clustering. The following code runs over k groups where k is between 1
to 10.</p>
<pre class="r"><code>merged_data =
  read_csv(&quot;data/Merged_expectation.csv&quot;) %&gt;% 
  filter(year == 2015) %&gt;% 
  select(une_life,alcohol, bmi, measles, basic_water, che_gdp, une_gni, une_literacy, PM_value) %&gt;% 
  drop_na()

X_var = 
  merged_data %&gt;% 
  select(alcohol, bmi, measles, basic_water, che_gdp, une_gni, une_literacy, PM_value)
Y_var = 
outcomes = merged_data %&gt;% 
  select(une_life)


#Scale X variable
Scale_X = X_var %&gt;% 
  na.omit() %&gt;% 
  scale()


fviz_nbclust(Scale_X, kmeans, method = &quot;silhouette&quot;) + 
  theme_bw()</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Here, we use silhouette method, which focus on how similar a point is
within-cluster in comparison with other clusters <a
href="https://www.analyticsvidhya.com/blog/2021/05/k-mean-getting-the-optimal-number-of-clusters/#:~:text=The%20silhouette%20coefficient%20or%20silhouette,to%20other%20clusters%20(separation).">paper</a>.
Based on the result, we discover that k =2,3 and 4 all has the highest
sihouette width. k reaches its optimal value when k=4 and the optimal
value coincide with our chosen k for k mean imputation value.</p>
<pre class="r"><code># get the kmean result and get the clusters
k_result = 
  kmeans(x = X_var, centers = 4)

#Create the overall dataframe with combined Xvar Yvar and cluster
Allvalues = 
  X_var %&gt;% 
  broom::augment(k_result, .) %&gt;% 
  cbind(Y_var,.)




# Plot predictor clusters against outcomes
ggplot(data = Allvalues, aes(x = une_gni, y = une_life, color = .cluster)) + 
  geom_point(size=3) + 
  labs(x = &quot;GNI&quot;, y = &quot;Life Expectancy&quot;, title = &quot;Life expectancy vs GNI after clustered&quot;, color = &quot;Cluster&quot;)</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Although the algorithm is high dimensional, it is always better to
visualize in a lower dimensional case when we only consider life
expectancy and the predictor values. Here I choose GNI as an example.
After clustering, we can clearly see that GNI with different clustered
are clustered at different locations. This clustering may coincide with
our previous classification with respect to different income group. High
income group indicated by yellow color clearly has a relatively high
life expectancy whereas low income group with low GNI value implied by
the green group has a low life expectancy.</p>
<pre class="r"><code># Visualize cluster plot with reduction to two dimensions
fviz_cluster(k_result, data = X_var, palette = &quot;Set2&quot;)</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>On the other hand, we plot based on the two highest variance
explained dimension determined by principal component analysis (PCA).
Most information are explained in the dimension 1 (44.4%) and dimension
2 (20.4%). As seen in the plot, only cluster 4 is clearly different from
the other clusters. Cluster 1,2 and 3 are all intercorrelated with each
other. This coincide with some of the time series plot in EDA part,
i.e. number of doctors per 10,000 people and educational spend, which
income groups overlapped with each other.</p>
<pre class="r"><code>imputed_data =
  read_csv(&quot;data/Imputed_expectation.csv&quot;) %&gt;% 
  filter(year == 2015)

X_var_imp = 
  imputed_data %&gt;% 
  select(alcohol, bmi, measles, basic_water, che_gdp, une_gni, une_literacy, PM_value)%&gt;% 
  na.omit() %&gt;% 
  scale()

Y_var_imp = 
outcomes = imputed_data %&gt;% 
  select(une_life)

# get the kmean result and get the clusters
k_result_imp = 
  kmeans(x = X_var_imp, centers = 4)

fviz_cluster(k_result_imp, data = X_var_imp, palette = &quot;Set2&quot;)</code></pre>
<p><img src="Linear_Regression_Model_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>After imputation with k=4 mean clustering, the four groups are now
separated from each other. This is reasonable because we impute with k=4
groups. Although the information may be biased, We can visualize that a
high dimension 1 will lead to a high values in dimension 2. To our
surprise, a low value in dimension 1 may also have a high value in
dimension 2. This may because that some of the low income countries with
low economic-related values may also have a high PM value.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
