---
title: "My awesome website"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# This is Jeff's awesome website

This is an plotly page

# Load packages and data
```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


Let's get some data
```{r}
data("nyc_airbnb")
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2 ) %>%
  select(
    borough = neighbourhood_group, neighbourhood,price, room_type, lat, long,rating
    ) %>% 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
) %>% 
  drop_na(rating)
  
nyc_airbnb
```
Let's make a scatterplot!

```{r}
nyc_airbnb %>% 
  #combine Price with the price and make it to a string
  mutate(
    text_label = str_c("Price: ",price, "\nRating: ",rating)
 ) %>% 
  plot_ly(
    #x is plot feature, ~ means comes from 
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers",
    alpha =.5, text = ~text_label
  )
```


```{r}
nyc_airbnb %>% 
  mutate(neighbourhood= fct_reorder(neighbourhood,price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood,
          type = "box")
```

Can we make a bar plot?
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood= fct_reorder(neighbourhood,n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n,
          type = "bar")
```

## ggplotly
```{r}
#less interactive. better to directly use plot_ly
gap_scatterplot = 
  nyc_airbnb %>% 
  ggplot(aes(x=lat, y = long, color = price))+
  geom_point()

ggplotly(gap_scatterplot)
```









